### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by JohnWilliamsArtist**
Changed Strap Line.

### CODE REVIEW

**Comment by drnw** [comment]
Cool! If you are happy to edit HTML that's great. Otherwise, my intention is to break it into Markdown files so you don't have to worry about HTML.

**Comment by JohnWilliamsArtist** [comment]
How about: I plod away with HTML for the mean time & we can review when I
hit a wall?

John Williams
Scottish Contemporary Artist

**Comment by drnw** [comment]
That sounds like a good plan :-) I am sure you can handle HTML. However, not everyone can. At some point I want to convert you to Markdown. I want to understand how effective it is for lay people and what support I may have to provide.

**Comment by drnw** [comment]
Once you have made the edits you want I can set the domain name to point to Github rather than Amazon (the current production site).

**Comment by JohnWilliamsArtist** [comment]
OK we'll convert to markdown as soon as its convenient for you...

John Williams
Scottish Contemporary Artist

**Comment by drnw** [comment]
On the HTML side, how comfortable are you working without a preview? What (if any) steps would you take to preview your changes before committing?

**Comment by JohnWilliamsArtist** [comment]
preview seems sensible - everyone makes mistakes but no ones gonna get
killed & if I know you there to jump in then Im happy to do without a net.

My preview step would be : Ask you to comment...

John Williams
Scottish Contemporary Artist

**Comment by JohnWilliamsArtist** [comment]
Actually on a selfy project like this I'd just go live with edit s and fix
any cockups as and when....

**Comment by drnw** [comment]
I concur. So when you make changes you can commit directly to the Master branch and these will instantly be published. Knock yourself out & let me know when your Github Pages are ready to have www.johnwilliamsartist.com pointing at them.

**Comment by JohnWilliamsArtist** [comment]
Will do... Im thinking two to three days if i dont blow-up anything.

John Williams
Scottish Contemporary Artist

**Pull request merged**
